### ISSUE TITLE
exception-logging is showing stacktrace with MESSAGE_ONLY option

### ISSUE THREAD

**Issue by bwgjoseph** [wimdeblauwe/error-handling-spring-boot-starter#65]
Hi,

I'm using `3.4.0`, given the following endpoint

```java
@GetMapping
public Person get() {
    throw new RuntimeException("testing");
}
```

And no configuration, because default is `MESSAGE_ONLY`

```yaml
error:
  handling:
    exception-logging: MESSAGE_ONLY
```

The output will be

```log
2023-03-12 02:16:51.348 ERROR 279524 --- [nio-8080-exec-2] i.g.w.e.LoggingService                   : testing

java.lang.RuntimeException: testing
        at com.bwgjoseph.springbootdebeziummongodbes.mongo.PersonController.get(PersonController.java:51) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        // omitted
```

If you change the configuration to 

```yaml
error:
  handling:
    exception-logging: WITH_STACKTRACE
```

The output is exactly the same.

I think the expected output for `MESSAGE_ONLY` should be (1 liner)

```log
2023-03-12 02:16:51.348 ERROR 279524 --- [nio-8080-exec-2] i.g.w.e.LoggingService                   : testing
```

Am I right?

Thanks!

**Comment by wimdeblauwe** [comment]
Yes, normally you should only get 1 line of output by default. Do you have a small reproducer for this?

**Comment by bwgjoseph** [comment]
Sure, you can grab it at https://github.com/bwgjoseph/spring-boot-error-handling-bug

**Comment by wimdeblauwe** [comment]
Found the problem, see PR #71

**Comment by wimdeblauwe** [comment]
Version 3.4.1 is released with a fix for this.
